# Generated by Django 5.2.16 on 2026-07-17 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('action', models.CharField(max_length=255)),
                ('is_pleasant', models.BooleanField(default=False)),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Периодичность выполнения в днях: от 1 до 7.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('reward', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveSmallIntegerField(help_text='Предполагаемое время выполнения в секундах.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('is_public', models.BooleanField(default=False)),
                ('next_notification_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('time', 'id'),
            },
        ),
    ]
