# Generated by Django 5.2.16 on 2026-07-17 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_as_reward_for', to='habits.habit'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('periodicity__gte', 1), ('periodicity__lte', 7)), name='habit_periodicity_between_1_and_7'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', 1), ('duration__lte', 120)), name='habit_duration_between_1_and_120'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('related_habit__isnull', True), ('reward', ''), _connector='OR'), name='habit_not_both_related_and_reward'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('is_pleasant', False), models.Q(('related_habit__isnull', True), ('reward', '')), _connector='OR'), name='pleasant_habit_without_reward_or_related'),
        ),
    ]
